apply plugin: 'com.android.application'

android {
    namespace 'org.segin.bfinterpreter'
    compileSdkVersion 28

    defaultConfig {
        applicationId "org.segin.bfinterpreter"
        minSdkVersion 14
        targetSdkVersion 28
        versionCode 1
        versionName "1.0"
    }

    buildTypes {
        release {
            minifyEnabled false
        }
    }
    // The project uses Java 7 as specified in the .iml file
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_7
        targetCompatibility JavaVersion.VERSION_1_7
    }
}

dependencies {
    implementation 'androidx.appcompat:appcompat:1.0.0'
}